Traceback (most recent call last):
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/rwegener/miniconda3/envs/sarp/lib/python3.13/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
metadata = {
    'location': 'Nairobi', 
    'quality_flag': 5
    'zenith': 60, 
    'clouds': True,
    'data_center': ['LPDAAC', 'ASDC'],
}
metadata['Zenith"] == '7'
rotated_zenith = metadata['zenith'] + 90
print(rotated_zenith)
------------------


[0;36m  Cell [0;32mIn[1], line 8[0;36m[0m
[0;31m    metadata['Zenith"] == '7'[0m
[0m                            ^[0m
[0;31mSyntaxError[0m[0;31m:[0m unterminated string literal (detected at line 8)


